hotelApplication/Controllers/MainController.cs
using hotelApplication.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace hotelApplication.Controllers
{
    
    public class MainController : Controller
    {
        ApplicationContext context;
        public MainController(ApplicationContext application)
        {
            context = application;
        }
        
        public IActionResult Example()
        {
            return View();
        }

        public IActionResult house()
        {
            return View();
        }

        public IActionResult provider()
        {
            return View();
        }

        public IActionResult events()
        {
            return View();
        }

        public IActionResult rent()
        {
            return View();
        }


        public IActionResult brone()
        {
            return View();
        }


        [Authorize(Roles = "admin")]
        public IActionResult AdminPage()
        {
            return View();
        }


    }
}

hotelApplication/Controllers/ReservationController.cs
using hotelApplication.Models;
using hotelApplication.ViewModels;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace hotelApplication.Controllers
{
    public class ReservationController : Controller
    {
        ApplicationContext context;

        public ReservationController(ApplicationContext _db)
        {
            context=_db;
        }
        public IActionResult Index()
        {
            return View(context.Reservations.ToList());
        }

        [HttpGet]
        public ActionResult Create(int? id)
        {
            if (id == null) { return RedirectToAction("Index"); }
            ViewBag.RoomId = id;
            var model = context.Rooms.FirstOrDefault(m => m.Id == id);
            return View(model);
        }


        [HttpPost]
        public async Task<ActionResult> Create(ReservationViewModel model)
        {            

            if (ModelState.IsValid)
            {
                Reservation reservation = new Reservation
                {
                    Id = model.Id,
                    UserId = model.UserId,
                    RoomId = model.RoomId,
                    FirstName = model.FirstName,
                    Name = model.Name,
                    LastName = model.LastName,
                    FirstDate = model.FirstDate,
                    LastDate = model.LastDate
                };
                context.Reservations.Add(reservation);
                await context.SaveChangesAsync();
                return RedirectToAction("Example","Main");
            }

            return View(model);
        }
    }
}

hotelApplication/Controllers/RolesController.cs
using hotelApplication.Models;
using hotelApplication.ViewModels;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace hotelApplication.Controllers
{
    [Authorize(Roles = "admin")]
    public class RolesController : Controller
    {
        RoleManager<IdentityRole> _roleManager;
        UserManager<User> _userManager;

        public RolesController(RoleManager<IdentityRole> roleManager, UserManager<User> userManager)
        {
            _roleManager = roleManager;
            _userManager = userManager;
        }


        public IActionResult Index()
        {
            return View(_roleManager.Roles.ToList());
        }


        [HttpGet]
        public IActionResult Create()
        {
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> Create(string name)
        {
            if (!string.IsNullOrEmpty(name))
            {
                IdentityResult result = await _roleManager.CreateAsync(new IdentityRole(name));
                if (result.Succeeded)
                {
                    return RedirectToAction("Index");
                }
                else
                {
                    foreach(var error in result.Errors)
                    {
                        ModelState.AddModelError(string.Empty, error.Description);
                    }
                }
            }
            return View(name);
        }

        [HttpPost]
        public async Task<IActionResult> Delete(string id)
        {
            IdentityRole role = await _roleManager.FindByIdAsync(id);
            if (role != null)
            {
                IdentityResult result = await _roleManager.DeleteAsync(role);
            }
            return RedirectToAction("Index");
        }

        public IActionResult UserList() => View(_userManager.Users.ToList());

        public async Task<IActionResult> Edit(string userId)
        {
            User user = await _userManager.FindByIdAsync(userId);
            if (user != null)
            {
                // получем список ролей пользователя
                var userRoles = await _userManager.GetRolesAsync(user);
                var allRoles = _roleManager.Roles.ToList();
                ChangeRoleViewModel model = new ChangeRoleViewModel
                {
                    UserId = user.Id,
                    UserEmail = user.Email,
                    UserRoles = userRoles,
                    AllRoles = allRoles
                };
                return View(model);
            }
            return NotFound();
        }

        [HttpPost]
        public async Task<IActionResult> Edit(string userId, List<string> roles)
        {
            // получаем пользователя
            User user = await _userManager.FindByIdAsync(userId);
            if (user != null)
            {
                // получем список ролей пользователя
                var userRoles = await _userManager.GetRolesAsync(user);
                // получаем все роли
                var allRoles = _roleManager.Roles.ToList();
                // получаем список ролей, которые были добавлены
                var addedRoles = roles.Except(userRoles);
                // получаем роли, которые были удалены
                var removedRoles = userRoles.Except(roles);

                await _userManager.AddToRolesAsync(user, addedRoles);

                await _userManager.RemoveFromRolesAsync(user, removedRoles);

                return RedirectToAction("UserList");
            }

            return NotFound();
        }
    }
}

hotelApplication/Views/Main/AdminPage.cshtml
@{
    Layout = null;
}
<head>
    <link rel="stylesheet" href="~/Content/css/reset.css">
    <link rel="stylesheet" href="~/Content/css/slick.css">
    <link rel="stylesheet" href="~/Content/css/jquery.fancybox.css">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <link rel="stylesheet" href="~/Content/css/animate.css">
    <link rel="stylesheet" href="~/Content/css/style.css">
</head>
<body>
    <header class="HeaderMain">
        <div class="container">
            <div class="HeaderElementContact">
                <div class="HeadLogo">
                    <a asp-controller="Main" asp-action="Example">
                        <img src="~/Content/logo.png" alt="Image" class="logoH">

                    </a>
                </div>

                <div class="Contact">
                    <img src="~/Content/icon1.png" alt="Image" class="Icon">
                    <h3 class="Contact-title ">
                        Вышка
                    </h3>
                    <p class="Contact-text">
                        Астраханская обл., с. Вышка
                    </p>

                </div>
                <div class="Contact Contact-phone">
                    <img src="~/Content/icon2.png" alt="Image" class="Icon">
                    <h3 class="Contact-title">
                        +7 (926) 326-72-63
                    </h3>
                    <p class="Contact-text">
                        Телефон для связи
                    </p>

                </div>
                <div class="Contact Contact-mail">
                    <img src="~/Content/icon3.png" alt="Image" class="Icon">
                    <h3 class="Contact-title">
                        info@mail.ru
                    </h3>
                    <p class="Contact-text">
                        Напишите нам
                    </p>
                </div>
            </div>

            <nav class="menu">
                <ul class="menu__list" style="  padding-left: 0px;">
                    <li><a class="btn btn-sm sign-up" asp-controller="Main" asp-action="Example">Главная</a></li>
                    <li><a class="btn btn-sm sign-up" href="#card1">Бронирование</a></li>
                    <li>
                        <div class="btn-group ">
                            <button class="btn btn-sm dropdown-toggle sign-up" type="button" data-bs-toggle="dropdown" aria-expanded="false">
                                Услуги
                            </button>

                            <ul class="dropdown-menu" aria-labelledby="dropdownMenuLink">
                                <li><a class="dropdown-item " asp-controller="Main" asp-action="events">Мероприятия</a></li>
                                <li><a class="dropdown-item " asp-controller="Main" asp-action="rent">Аренда техники</a></li>
                                <li><a class="dropdown-item " asp-controller="Main" asp-action="provider">Дополнительные услуги</a></li>
                            </ul>

                        </div>


                    </li>
                    <li><a class="btn btn-sm sign-up" href="#">О нас</a></li>
                    <li><a class="btn btn-sm sign-up" href="#">Контакты</a></li>

                    @if (User.Identity.IsAuthenticated)
                    {

                        <li><p class="menu__list">@User.Identity.Name</p></li>
                        <li>
                            <form method="post" asp-controller="Account" asp-action="Logout">
                                <input type="submit" class="btn btn-sm sign-up" value="Выход" />

                            </form>
                        </li>


                    }
                    else
                    {
                        <li><a class="btn btn-sm sign-up" asp-controller="Account" asp-action="Login">Войти</a></li>
                        <li><a class="btn btn-sm sign-up" asp-controller="Account" asp-action="Register">Зарегистрироваться</a></li>

                    }
                </ul>

            </nav>
        </div>
    </header>
    <main>
        <div class="container">
            <div class="row">
                <div class="col">
                </div>
                <div class="col order-5">
                </div>
                <div class="col order-1">
                    
                    <table class="table">
                        <thead>
                            <tr>
                                <th scope="col">Номера</th>
                                <th scope="col">Пользователи</th>
                                <th scope="col">Роли</th>
                            </tr>
                        </thead>
                        <tbody>
                           
                                <tr>
                                    <td><a asp-action="Index" asp-controller="Room" class="btn btn-outline-dark">Номера</a></td>
                                    <td><a asp-action="Index" asp-controller="Users" class="btn btn-outline-dark">Пользователи</a></td>
                                    <td>
                                        <a asp-action="UserList" asp-controller="Roles" class="btn btn-outline-dark">Роли</a>
                                    </td>
                                </tr>

                            
                        </tbody>
                    </table>
                </div>
            </div>
        </div>


</main>
   
</body>

hotelApplication/Views/Main/brone.cshtml
@{
    Layout = null;
}
<head>
    <link rel="stylesheet" href="~/Content/css/reset.css">
    <link rel="stylesheet" href="~/Content/css/slick.css">
    <link rel="stylesheet" href="~/Content/css/jquery.fancybox.css">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <link rel="stylesheet" href="~/Content/css/animate.css">
    <link rel="stylesheet" href="~/Content/css/style.css">
</head>
<body>
    <header class="HeaderMain">
        <div class="container">
            <div class="HeaderElementContact">
                <div class="HeadLogo">
                    <a asp-controller="Main" asp-action="Example">
                        <img src="~/Content/logo.png" alt="Image" class="logoH">

                    </a>
                </div>

                <div class="Contact">
                    <img src="~/Content/icon1.png" alt="Image" class="Icon">
                    <h3 class="Contact-title ">
                        Вышка
                    </h3>
                    <p class="Contact-text">
                        Астраханская обл., с. Вышка
                    </p>

                </div>
                <div class="Contact Contact-phone">
                    <img src="~/Content/icon2.png" alt="Image" class="Icon">
                    <h3 class="Contact-title">
                        +7 (926) 326-72-63
                    </h3>
                    <p class="Contact-text">
                        Телефон для связи
                    </p>

                </div>
                <div class="Contact Contact-mail">
                    <img src="~/Content/icon3.png" alt="Image" class="Icon">
                    <h3 class="Contact-title">
                        info@mail.ru
                    </h3>
                    <p class="Contact-text">
                        Напишите нам
                    </p>
                </div>
            </div>

            <nav class="menu">
                <ul class="menu__list">
                    <li><a class="btn btn-sm sign-up" asp-controller="Main" asp-action="Example">Главная</a></li>
                    <li><a class="btn btn-sm sign-up" href="#card1">Бронирование</a></li>
                    <li>
                        <div class="btn-group ">
                            <button class="btn btn-sm dropdown-toggle sign-up" type="button" data-bs-toggle="dropdown" aria-expanded="false">
                                Услуги
                            </button>

                            <ul class="dropdown-menu" aria-labelledby="dropdownMenuLink">
                                <li><a class="dropdown-item " asp-controller="Main" asp-action="events">Мероприятия</a></li>
                                <li><a class="dropdown-item " asp-controller="Main" asp-action="rent">Аренда техники</a></li>
                                <li><a class="dropdown-item " asp-controller="Main" asp-action="provider">Дополнительные услуги</a></li>
                            </ul>

                        </div>


                    </li>
                    <li><a class="btn btn-sm sign-up" href="#">О нас</a></li>
                    <li><a class="btn btn-sm sign-up" href="#">Контакты</a></li>

                    @if (User.Identity.IsAuthenticated)
                    {

                        <li><p class="menu__list">@User.Identity.Name</p></li>
                        <li>
                            <form method="post" asp-controller="Account" asp-action="Logout">
                                <input type="submit" class="btn btn-sm sign-up" value="Выход" />

                            </form>
                        </li>


                    }
                    else
                    {
                        <li><a class="btn btn-sm sign-up" asp-controller="Account" asp-action="Login">Войти</a></li>
                        <li><a class="btn btn-sm sign-up" asp-controller="Account" asp-action="Register">Зарегистрироваться</a></li>

                    }
                </ul>

            </nav>
        </div>
    </header>

    <div class="container">
        <div class="row">
            <div hidden class="col">

            </div>
            <div hidden class="col order-5">

            </div>
            <div class="col order-1" style=" margin-top: 50px;">

            </div>
        </div>
    </div>



                
                <div class="form-popup" id="myForm">
                    <form method="post" asp-controller="Reservation" asp-action="Create" class="form-container">
                        <h2>Бронирование</h2> <br />

                        <label for="name"><b>Имя</b></label>
                        <input type="text" placeholder="Ваше имя" name="name" required>
                        <label for="lastname"><b>Фамилия</b></label>
                        <input type="text" placeholder="Ваша фамилия" name="lastname" required>
                        <label for="phone"><b>Телефон</b></label>
                        <input type="text" placeholder="Ваш номер телефона" name="phone" required>

                        <label for="email"><b>Е-мейл</b></label>
                        <input type="text" placeholder="Ваш е-мейл" name="email" required>
                        <label for="number"><b>Количество человек</b></label>
                        <input type="text" placeholder="Сколько вас приедет" name="number" required>
                        
                        <input type="submit" class="btn btn-sm sign-up" value="Бронировать"  />

                            
                        
                        <button type="button" class="btn cancel" onclick="closeForm()">Закрыть</button>
                    </form>
                </div>

</body>

hotelApplication/Views/Main/house.cshtml
@{
    Layout = null;
}
<head>
    <link rel="stylesheet" href="~/Content/css/reset.css">
    <link rel="stylesheet" href="~/Content/css/slick.css">
    <link rel="stylesheet" href="~/Content/css/jquery.fancybox.css">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <link rel="stylesheet" href="~/Content/css/animate.css">
    <link rel="stylesheet" href="~/Content/css/style.css">
</head>
<body>
    <header class="HeaderMain">
        <div class="container">
            <div class="HeaderElementContact">
                <div class="HeadLogo">
                    <a asp-controller="Main" asp-action="Example">
                        <img src="~/Content/logo.png" alt="Image" class="logoH">

                    </a>
                </div>

                <div class="Contact">
                    <img src="~/Content/icon1.png" alt="Image" class="Icon">
                    <h3 class="Contact-title ">
                        Вышка
                    </h3>
                    <p class="Contact-text">
                        Астраханская обл., с. Вышка
                    </p>

                </div>
                <div class="Contact Contact-phone">
                    <img src="~/Content/icon2.png" alt="Image" class="Icon">
                    <h3 class="Contact-title">
                        +7 (926) 326-72-63
                    </h3>
                    <p class="Contact-text">
                        Телефон для связи
                    </p>

                </div>
                <div class="Contact Contact-mail">
                    <img src="~/Content/icon3.png" alt="Image" class="Icon">
                    <h3 class="Contact-title">
                        info@mail.ru
                    </h3>
                    <p class="Contact-text">
                        Напишите нам
                    </p>
                </div>
            </div>

            <nav class="menu">
                <ul class="menu__list" style="  padding-left: 0px;">
                    <li><a class="btn btn-sm sign-up" asp-controller="Main" asp-action="Example">Главная</a></li>
                    <li><a class="btn btn-sm sign-up" href="#card1">Бронирование</a></li>
                    <li>
                        <div class="btn-group ">
                            <button class="btn btn-sm dropdown-toggle sign-up" type="button" data-bs-toggle="dropdown" aria-expanded="false">
                                Услуги
                            </button>

                            <ul class="dropdown-menu" aria-labelledby="dropdownMenuLink">
                                <li><a class="dropdown-item " asp-controller="Main" asp-action="events">Мероприятия</a></li>
                                <li><a class="dropdown-item " asp-controller="Main" asp-action="rent">Аренда техники</a></li>
                                <li><a class="dropdown-item " asp-controller="Main" asp-action="provider">Дополнительные услуги</a></li>
                            </ul>

                        </div>


                    </li>
                    <li><a class="btn btn-sm sign-up" href="#">О нас</a></li>
                    <li><a class="btn btn-sm sign-up" href="#">Контакты</a></li>

                    @if (User.Identity.IsAuthenticated)
                    {

                        <li><p class="menu__list">@User.Identity.Name</p></li>
                        <li>
                            <form method="post" asp-controller="Account" asp-action="Logout">
                                <input type="submit" class="btn btn-sm sign-up" value="Выход" />

                            </form>
                        </li>


                    }
                    else
                    {
                        <li><a class="btn btn-sm sign-up" asp-controller="Account" asp-action="Login">Войти</a></li>
                        <li><a class="btn btn-sm sign-up" asp-controller="Account" asp-action="Register">Зарегистрироваться</a></li>

                    }
                </ul>

            </nav>
        </div>
    </header>
    <main>
        <div class="container">
            <div class="main-title">
                <p class="main-text">Домик на двоих</p>
            </div>
            <div id="carouselControls" class="carousel slide animated fadeInLeft" data-bs-ride="carousel">
                <div class="carousel-inner">
                    <div class="carousel-item active">
                        <img class="d-block w-100" src="~/Content/house1-1.jpg" alt="First slide">
                    </div>
                    <div class="carousel-item">
                        <img class="d-block w-100" src="~/Content/house1-2.jpg" alt="Second slide">
                    </div>
                    <div class="carousel-item">
                        <img class="d-block w-100" src="~/Content/house1-3.jpg" alt="Third slide">
                    </div>
                </div>
                <a class="carousel-control-prev" href="#carouselControls" role="button" data-bs-slide="prev">
                    <span class="carousel-control-prev-icon" aria-hidden="true"></span>
                    <span class="sr-only"></span>
                </a>
                <a class="carousel-control-next" href="#carouselControls" role="button" data-bs-slide="next">
                    <span class="carousel-control-next-icon" aria-hidden="true"></span>
                    <span class="sr-only"></span>
                </a>
            </div>
            <section class="infoHouse site-section1 animated">
                <div class="elementor-widget-container">
                    <div class="elementor-text-editor elementor-clearfix"><p><strong>Дом на двоих</strong><br />Уютный дом на 2-х человек. Рядом с домом располагается беседка с зоной для барбекю. В комплектацию дома входит постельное белье, полотенца, посуда и столовые приборы по количеству спальных мест.<br /></p></div>
                </div>
                <div class="Info-body">
                    <div class="elementor-element elementor-element-639019b elementor-widget elementor-widget-text-editor" data-id="639019b" data-element_type="widget" data-widget_type="text-editor.default">
                        <div class="elementor-widget-container">
                            <div class="elementor-text-editor elementor-clearfix"><p><strong>В доме:</strong><br />&#8211; Спальня с 2-мя односпальными кроватями<br />&#8211; Прикроватная тумбочка -1 шт,<br />&#8211; Светильник — 2шт.<br />&#8211; Цифровой ТВ<br />&#8211; Стойка вешалка<br />&#8211; Сплит-система<br />&#8211; Плотные шторы для затемнения <br />&#8211; Санузел <br />&#8211; Входная зона, совмещенная с обеденной:<br />&#8211; Стол, стулья на двоих<br />&#8211; Настенная вешалка<br />&#8211; Тумбочка, зеркало<br /></p><p><strong>Кухонная зона:</strong><br />&#8211; Кухонный блок<br />&#8211; Электрический чайник<br />&#8211; Холодильник<br />&#8211; Микроволновая печь<br />&#8211; Посуда, столовые приборы на 2-х и кухонные принадлежности.</p><p> </p><p> </p><p> </p><p> </p></div>
                        </div>
                    </div>
                    <div class="DataPick">
                       <p><a asp-action="Index" asp-controller="Reservation"  class="btn btn-primary py-3 px-4">Бронировать</a></p>
                          
                    </div>
                    <div class="elementor-element elementor-element-a47f500 elementor-widget elementor-widget-text-editor" data-id="a47f500" data-element_type="widget" data-widget_type="text-editor.default">
                        <div class="elementor-widget-container">
                            <div class="elementor-text-editor elementor-clearfix">
                                <p><em><strong>Дополнительные услуги</strong></em></p>
                                <ul class="servic">
                                    <li><a href="#">Посещение бассейна .... рублей/час</a></li>
                                    <li><a href="#">Баня .... рублей/час</a></li>
                                    <li><a href="#">Приготовление трофеев</a></li>
                                    <li><a href="#">Использование собственного флота</a></li>
                                    <li><a href="#">Организация охоты на водоплавающую дичь</a></li>
                                    <li><a href="#">Экскурскии на лотосовые поля</a></li>
                                    <li><a href="#">Прокат выболовных снастей</a></li>
                                    <li><a href="#">Аренда флота</a></li>
                                </ul>
                            </div>

                        </div>
                    </div>
                </div>
            </section>
        </div>


    </main>





    <footer id="footer" class="footer">
        <div class="container">
            <p class="credits">© Все права защищены.</p>
        </div>
    </footer>

    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
    <script src="~/Content/js/slick.min.js"></script>
    <script src="~/Content/js/jquery.fancybox.min.js"></script>
    <script src="~/Content/js/main.js"></script>
</body>